### ISSUE TITLE
Please provide screenshots

### ISSUE THREAD

**Issue by abby-d** [zesty-io/zesty-org#8]
Please provide screenshots for the views described in https://github.com/zesty-io/zesty-org/blob/master/services/web-engine/interface/content/README.md

**Comment by abby-d** [comment]
There's also a typo (@) in the first paragraph of the Entry Editing section on that page:
> This view shows fields with the current content value(s) in the main section and publishing history and status to the right.**_@_**

**Comment by kakoga** [comment]
> There's also a typo (@) in the first paragraph of the Entry Editing section on that page:
> 
> > This view shows fields with the current content value(s) in the main section and publishing history and status to the right.**_@_**

fixed - thank you!

**Comment by kakoga** [comment]
> Please provide screenshots for the views described in https://github.com/zesty-io/zesty-org/blob/master/services/web-engine/interface/content/README.md

Thanks for your feedback!! We appreciate it. I just updated the doc with images (and clarified some of the text as well).
